project:
  type: website
  output-dir: docs

website:
  title: "AI vs. Non-AI Job Growth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_analysis.qmd
        text: "Data Analysis"

format:
  html:
    toc: true

bibliography: references.bib
csl: csl/econometrica.csl
