project:
  type: website
  output-dir: docs

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: data_analysis.qmd
        text: "Data Analysis"

format:
  html:
    toc: true
